require("BSgenome.Mmusculus.UCSC.mm10") || stop("can not load mm10 BSgenome.")
require("BSgenome.Hsapiens.UCSC.hg19") || stop("can not load hg19 BSgenome.")
require("TxDb.Mmusculus.UCSC.mm10.knownGene") || stop("can not load mm10 TxDb")
require("rtracklayer") || stop("can not load rtracklayer.")
require("EnsDb.Hsapiens.v86") || stop("can not load human EnsDb")
require("EnsDb.Mmusculus.v79") || stop("can not load mouse EnsDb")
require("limma") || stop("can not load limma")
BiocGenerics:::testPackage("InPAS")
