require("BSgenome.Mmusculus.UCSC.mm10") || stop("can not load mm10 BSgenome.")
require("TxDb.Mmusculus.UCSC.mm10.knownGene") || stop("can not load mm10 TxDb")
require("rtracklayer") || stop("can not load rtracklayer.")
require("GenomicRanges") || stop("can't load GenomicRanges")
require("limma") || stop("can not load limma")
BiocGenerics:::testPackage("InPAS")
