#' Convert coverage of a single sample in bedgraph format to Rle
#' 
#' Convert coverage of a single sample in the bedgraph format to an object of 
#'   [S4Vectors::Rle-class]
#'
#' @param bedgraph A character(1) of a file name of bedgraph generated by
#'   bedtools. eg: bedtools genomecov -bga -split -ibam $bam > $bedgraph
#' @param tag Name tag used to label each input bedgraph
#' @param sqlite_db A path to the SQLite database for InPAS, i.e. the output of
#'   setup_sqlitedb().
#' @param genome An object of [BSgenome::BSgenome-class]
#' @param removeScaffolds logical(1), whether the scaffolds should be removed
#'   from the genome
#' @param hugeData logical(1). Is this dataset consume too much memory? if it is
#'   TRUE, the coverage will be saved into tempfiles.
#' @param outdir A path to a directory/folder where output is written
#' 
#' @return If hugeData is set "FALSE", the function returns a list containing 
#'   read coverage and total depth for a bedgraph file. The first list element
#'   contains a list of Rle instances of [S4Vectors::Rle-class] representing
#'   read coverage for each chromosome, with the chromosome names starting 
#'   with "chr" as names. The second element contains total depth. Otherwise,
#'   the returned value is a character(1), with tag as the name.
#'   
#' @export
#' @import BiocParallel S4Vectors
#' 

bedgraph2RleCov <- function(bedgraph,
                            tag,
                            sqlite_db,
                            genome,
                            removeScaffolds = FALSE,
                            hugeData = FALSE,
                            outdir = NULL){
    if (missing(genome)) {
        stop("genome is required.")
    }
    if (!is(genome, "BSgenome")) {
        stop("genome must be an object of BSgenome.")
    }
    if (missing(tag) || missing(bedgraph)) {
        stop("tags and bedgraphs are required.")
    }
    if (length(bedgraph) != 1 || length(tag) != 1) {
        stop("length of bedgraph must be 1")
    }
    if (!file.exists(bedgraph)) {
        stop("bedgraph file does not exist")
    }
    if (hugeData && is.null(outdir))
    {
        stop("A writable output directory is", 
             " required for store huge coverage data!")
    }
    
    if (hugeData && missing(sqlite_db) || !file.exists(sqlite_db)){
        stop("The SQLite database for InPAS is required for hugeData!")
    }
    
    ## A vector of chromosome lengths, with chromosome names as names 
    seq_length <- seqLen(genome = genome, 
                         removeScaffolds = removeScaffolds)
    
    conn <- file(bedgraph, "r")
    RleList <- list(tag = list(), depth = 0)
    
    i <- 1
    runLen <- vector("integer")
    runVal <- vector("integer")
    seqname <- ""
    prev_end <- 0
    
    while(length(line <- readLines(conn, n = 1)) > 0){
        cur_line <- unlist(strsplit(line, split = "\t"))
        if (length(cur_line) != 4){
            stop("The bedgraph file is not correct!")
        }
        
        cur_vals <- as.integer(cur_line[2:4])
        
        ## define the helper function once
        if (i == 1){
            process_bedgraph <- function(){
                if (cur_vals[1] != prev_end){
                    runLen[i] <<- cur_vals[1] - prev_end
                    runVal[i] <<- 0
                    i <<- i +1
                }
                runLen[i] <<- cur_vals[2] - cur_vals[1]
                runVal[i] <<- cur_vals[3]
                prev_end <<- cur_vals[2]
            }
        }
        
        if (seqname == ""){
            seqname <- cur_line[1]
            ## Add the first zero coverage regions
            process_bedgraph()
        } else if (seqname == cur_line[1]) {
            ## Add gap regions
            process_bedgraph()
        } else { # start with new chromosome
            runLen[i] <- seq_length[seqname] - prev_end
            runVal[i] <- 0
            RleList$tag[[seqname]] <- Rle(runVal, runLen)

            seqname <- cur_line[1]
            i <- 1
            runLen <- vector("integer")
            runVal <- vector("integer")
            prev_end <- 0
            ## Add the first zero coverage regions
            process_bedgraph()
        }
        i <- i +1
    }
    
    if (i == 1){stop("The bedgraph file is empty!")}
    
    runLen[i] <- seq_length[seqname] - prev_end
    runVal[i] <- 0
    RleList$tag[[seqname]] <- Rle(runVal, runLen)
    close(conn)
    
    uncovered_chr <- names(seq_length)[!names(seq_length) %in% 
                                           names( RleList[[1]])]
    for (chr in uncovered_chr){
        runLen <- seq_length[chr]
        runVal <- 0
        RleList$tag[[chr]] <-  Rle(runVal, runLen)
    }
    
    ## total depth per sample
    depth <- sapply(RleList$tag, function(.cvg) {
        sum(as.double(runValue(.cvg)) * runLength(.cvg))
    })
    depth <- sum(depth)
    names(depth) <- tag
    names(RleList)[1] <- tag
    RleList$depth <- depth
    
    if (hugeData)
    {
        ## save coverage per chromosome of each samples as files into a 
        ## directory named by chromosome ID
        filenames <- lapply(names(seq_length), function(chr){
            od <- file.path(outdir, "samplewise_RleCov", chr)
            if (!dir.exists(od))
            {
                dir.create(od, recursive = TRUE)
            }
            od <- normalizePath(od)
            filename <- file.path(od, 
                                  paste(tag, chr, 
                                        Sys.Date(), 
                                        "RleCov.RDS",sep = "_"))
            saveRDS(RleList[[tag]][chr], file = filename)
            filename
        })
        names(filenames) <- names(seq_length)
        filenames <- list(fn = filenames, depth = depth)
        names(filenames)[1] <- tag
        
        filename_df <- data.frame(tag = tag, chr = names(seq_length), 
                                  coverage_file = unlist(filenames[[1]]))
        
        db_conn <- dbConnect(drv = RSQLite::SQLite(), 
                             dbname= sqlite_db)
        ## add depth to the metadata table
        # err <- simpleError("SQL error: database is locked")
        # while (is(err, "simpleError"))
        # {
        #     err <- tryCatch({
                dbSendQuery(db_conn,
                             paste("UPDATE metadata SET depth = ",
                                    depth, "WHERE tag = ",
                                    names(depth), ";"))
                
                dbBegin(db_conn)
                res <- dbSendQuery(db_conn, 
                                   "INSERT INTO 
                           sample_coverage (tag, chr, coverage_file) 
                           VALUES (:tag, :chr, :coverage_file);", 
                                   filename_df)
                dbClearResult(res)
                dbCommit(db_conn)
                # }, 
                # error = function(err) err)
            
        #     if (!is(err, "simpleError")){
        #         stop("Some tag is not specified in the metadata")
        #     }
        # }
        dbDisconnect(db_conn)

        # return files in a list of list, first element is sample tag 
        # named list containing filenames, second element contains 
        # total coverage depth of the sample
        filenames
    } else {
        RleList
    }
}


