#' do estimation of alternative polyadenylation and cleavage site in one step
#'
#' A wrapper function to discover alternative polyadenylation and cleavage site
#' in one step
#'
#' @param bedgraphs The file names of bedgraphs generated by bedtools. eg:
#'   bedtools genomecov -bga -split -ibam $bam -g mm10.size.txt > $bedgraph
#' @param genome an object of [BSgenome::BSgenome-class]
#' @param removeScaffolds logical(1), whether the scaffolds should be removed
#'   from the genome
#' @param utr3 output of utr3Annotation
#' @param TxDb an object of [GenomicFeatures::TxDb-class]
#' @param tags the names for each input bedgraphs
#' @param hugeData is s this dataset consume too much memory? if it is TRUE, the
#'   coverage will be saved into tempfiles.
#' @param ... parameters can be passed into tempfile. This is useful when you
#'   submit huge dataset to cluster.
#' @param gp1 tag names involved in group 1
#' @param gp2 tag names involved in group 2
#' @param window_size window size for novel distal position searching and
#'   adjusted polyA searching, default: 100
#' @param search_point_START start point for searching
#' @param search_point_END end point for searching
#' @param cutStart how many nucleotides should be removed from the start before
#'   search, 0.1 means 10 percent.
#' @param cutEnd how many nucleotides should be removed from the end before
#'   search, 0.1 means 10 percent.
#' @param coverage_threshold cutoff threshold for coverage in the region of
#'   short form
#' @param long_coverage_threshold cutoff threshold for coverage in the region of
#'   long form
#' @param background the range for calculating cutoff threshold of local
#'   background
#' @param adjust_distal_polyA_end If true, adjust distal polyA end by
#'   [cleanUpdTSeq::cleanUpdTSeq-package]
#' @param PolyA_PWM Position Weight Matrix of polyA
#' @param classifier An object of [cleanUpdTSeq::PASclassifier-class]
#' @param classifier_cutoff This is the cutoff used to assign whether a putative
#'   pA is true or false. This can be any floating point number between 0 and 1.
#'   For example, classifier_cutoff = 0.5 will assign an putative pA site with
#'   prob.1 > 0.5 to the True class (1), and any putative pA site with prob.1 <=
#'   0.5 as False (0).
#' @param shift_range the shift range for polyA site searching
#' @param method a character(1) vector. The available test method are #'
#'   "limma", "fisher.exact", "singleSample", "singleGroup"
#' @param normalize normalization method. It can be "none", "quantiles",
#'   "quantiles.robust","mean", or "median".
#' @param design the design matrix of the experiment, with rows corresponding to
#'   arrays and columns to coefficients to be estimated. Defaults to the unit
#'   vector meaning that the arrays are treated as replicates. See
#'   [stats::model.matrix()]
#' @param contrast.matrix numeric matrix with rows corresponding to coefficients
#'   in fit and columns containing contrasts. May be a vector if there is only
#'   one contrast. See [limma::makeContrasts()]
#' @param coef column number or column name specifying which coefficient or
#'   contrast of the linear model is of interest. see more [limma::topTable()].
#'   Default value: 1
#' @param P.Value_cutoff cutoff of P value
#' @param adj.P.Val_cutoff cutoff value for adjusted p.value
#' @param dPDUI_cutoff cutoff value for differential PAS (polyadenylation
#'   signal) usage index
#' @param PDUI_logFC_cutoff cutoff value for log2 fold change of
#'   PAS(polyadenylation signal) usage index
#' @param BPPARAM An optional [BiocParallel::BiocParallelParam-class] instance
#'   determining the parallel back-end to be used during evaluation, or a list
#'   of BiocParallelParam instances, to be applied in sequence for nested calls
#'   to bplapply
#'
#' @return  an object of [GenomicRanges::GRanges-class]
#' @export
#' @importFrom dplyr as_tibble mutate filter arrange bind_rows group_by
#'   left_join summarise n
#' @import GenomicRanges BiocParallel
#' @importClassesFrom IRanges IRanges
#'
#' @examples
#' if (interactive()) {
#'   library(BSgenome.Mmusculus.UCSC.mm10)
#'   library(TxDb.Mmusculus.UCSC.mm10.knownGene)
#'   path <- system.file("extdata", package = "InPAS")
#'   bedgraphs <- file.path(path, "Baf3.extract.bedgraph")
#'   data(utr3.mm10)
#'   res <- InPASWrapper(
#'     bedgraphs = bedgraphs, tags = c("Baf3"),
#'     genome = BSgenome.Mmusculus.UCSC.mm10,
#'     removeScaffolds = TRUE,
#'     method = "singleSample",
#'     utr3 = utr3.mm10, gp1 = "Baf3", gp2 = NULL,
#'     TxDb = TxDb.Mmusculus.UCSC.mm10.knownGene,
#'     search_point_START = 200,
#'     short_coverage_threshold = 15,
#'     long_coverage_threshold = 3,
#'     cutStart = 0, cutEnd = .2,
#'     hugeData = FALSE
#'   )
#'   res
#' }
InPASWrapper <- function(bedgraphs,
                         genome,
                         removeScaffolds = FALSE,
                         utr3, TxDb = NA,
                         tags, hugeData = FALSE, ...,
                         gp1, gp2,
                         window_size = 100,
                         search_point_START = 50,
                         search_point_END = NA,
                         cutStart = window_size,
                         cutEnd = 0,
                         coverage_threshold = 5,
                         long_coverage_threshold = 2,
                         background = c(
                           "same_as_long_coverage_threshold",
                           "1K", "5K", "10K", "50K"
                         ),
                         adjust_distal_polyA_end = TRUE,
                         PolyA_PWM = NA, classifier = NA,
                         classifier_cutoff = .8,
                         shift_range = window_size,
                         method = c(
                           "limma", "fisher.exact",
                           "singleSample", "singleGroup"
                         ),
                         normalize = c(
                           "none", "quantiles",
                           "quantiles.robust",
                           "mean", "median"
                         ),
                         design, contrast.matrix, coef = 1,
                         P.Value_cutoff = 0.05,
                         adj.P.Val_cutoff = 0.05,
                         dPDUI_cutoff = 0.3,
                         PDUI_logFC_cutoff = 0.59,
                         BPPARAM = NULL) {
  background <- match.arg(background)
  method <- match.arg(method)
  normalize <- match.arg(normalize)

  if (!missing(gp1) | !missing(gp2)) {
    if (!all(c(gp1, gp2) %in% tags)) {
      stop("gp1 and gp2 must be in tags")
    }

    if (missing(gp2)) gp2 <- NULL
    if (missing(gp1)) gp1 <- NULL
    groupList <- list(gp1 = gp1, gp2 = gp2)
  } else {
    groupList <- NULL
  }

  if (missing(gp2)) gp2 <- NULL
  if (missing(gp1)) gp1 <- NULL
  if (length(gp2) > 0) gp2 <- gp2[!is.na(gp2)]
  if (length(gp1) > 0) gp1 <- gp1[!is.na(gp1)]
  if (missing(design)) design <- NULL
  if (missing(contrast.matrix)) contrast.matrix <- NULL

  if (!missing(TxDb)) {
    if (background != "same_as_long_coverage_threshold") {
      stop("TxDb is missing when you want local background")
    } else {
      if (!is(TxDb, "TxDb")) {
        stop("TxDb must be an object of TxDb")
      }
    }
  }

  if (missing(genome) || missing(utr3)) {
    stop("genome and utr3 are required.")
  }
  if (!is(genome, "BSgenome")) {
    stop("genome must be an object of BSgenome.")
  }
  if (!is(utr3, "GRanges") |
    !all(utr3$feature %in% c("utr3", "next.exon.gap", "CDS"))) {
    stop("utr3 must be output of function of utr3Annotation")
  }

  if (length(gp2) < 1 | length(gp1) < 1) {
    samples <- unlist(groupList)
    samples <- samples[!is.na(samples)]
    if (length(samples) > 1) {
      if (method != "singleGroup") {
        stop("method should be singleGroup")
      }
    } else {
      if (length(samples) == 1) {
        if (method != "singleSample") {
          stop("method should be singleSample")
        }
      }
    }
  }

  ## step1 coverage
  coverage <-
    coverageFromBedGraph(bedgraphs,
      tags,
      genome,
      removeScaffolds = removeScaffolds,
      hugeData = hugeData, ...
    )

  ## step2 predict CPsites
  CPs <- CPsites(
    coverage = coverage,
    groupList = groupList,
    genome = genome, utr3 = utr3,
    window_size = window_size,
    search_point_START = search_point_START,
    search_point_END = search_point_END,
    cutStart = cutStart, cutEnd = cutEnd,
    adjust_distal_polyA_end = adjust_distal_polyA_end,
    background = background,
    TxDb = TxDb,
    removeScaffolds = removeScaffolds,
    coverage_threshold = coverage_threshold,
    long_coverage_threshold = long_coverage_threshold,
    PolyA_PWM = PolyA_PWM,
    classifier = classifier,
    classifier_cutoff = classifier_cutoff,
    shift_range = shift_range, BPPARAM = BPPARAM
  )

  ## step3 calculate usage
  res <- testUsage(
    CPsites = CPs,
    coverage = coverage,
    genome = genome,
    utr3 = utr3,
    method = method,
    normalize = normalize,
    design = design,
    contrast.matrix = contrast.matrix,
    coef = coef,
    gp1 = gp1, gp2 = gp2
  )

  if (hugeData) {
    removeTmpfile(coverage)
  }

  filterRes(res,
    gp1 = gp1, gp2 = gp2,
    background_coverage_threshold = long_coverage_threshold,
    P.Value_cutoff = P.Value_cutoff,
    adj.P.Val_cutoff = adj.P.Val_cutoff,
    dPDUI_cutoff = dPDUI_cutoff,
    PDUI_logFC_cutoff = PDUI_logFC_cutoff
  )
}

removeTmpfile <- function(coverage) {
  lapply(coverage, unlink)
}
